WITH source_data AS (
    SELECT 
        parse_json(message_body) AS raw_data,
        raw_data:"Payload"::Object:"AnyOfferChangedNotification"::Object:"OfferChangeTrigger"::ARRAY AS offer,
        raw_data:"Payload"::Object:"AnyOfferChangedNotification"::Object:"Offers"::ARRAY AS offers,
        parse_json(raw_data:"Payload"::Object:"AnyOfferChangedNotification"::Object:"Summary"::Object:"BuyBoxPrices") AS summary,
        raw_data:"Payload"::Object:"AnyOfferChangedNotification"::Object:"Summary"::Object:"ListPrice"::ARRAY AS ListPrice,
        parse_json(raw_data:"Payload"::Object:"AnyOfferChangedNotification"::Object:"Summary"::Object:"LowestPrices") AS LowestPrices,
        parse_json(raw_data:"Payload"::Object:"AnyOfferChangedNotification"::Object:"Summary"::Object:"NumberOfBuyBoxEligibleOffers") AS NumberOfBuyBoxEligibleOffers,
        parse_json(raw_data:"Payload"::Object:"AnyOfferChangedNotification"::Object:"Summary"::Object:"NumberOfOffers") AS NumberOfOffers,
        parse_json(raw_data:"Payload"::Object:"AnyOfferChangedNotification"::Object:"Summary"::Object:"SalesRankings") AS SalesRankings,
    FROM buybox.raw.bb_raw
),
flatten_payload AS (
    SELECT 
        raw_data:EventTime::TIMESTAMP AS EventTime,
        raw_data:NotificationMetadata:ApplicationId::STRING AS ApplicationId,
        raw_data:NotificationMetadata:NotificationId::STRING AS NotificationId,
        raw_data:NotificationMetadata:PublishTime::TIMESTAMP AS PublishTime,
        raw_data:NotificationMetadata:SubscriptionId::STRING AS SubscriptionId,
        raw_data:NotificationType::STRING AS NotificationType,
        raw_data:NotificationVersion::STRING AS NotificationVersion,
        offer.value:ASIN::STRING AS ASIN,    
        offer.value:ItemCondition::STRING AS ItemCondition,    
        offer.value:MarketplaceId::STRING AS MarketplaceId,    
        offer.value:OfferChangeType::STRING AS OfferChangeType,    
        offer.value:TimeOfOfferChange::TIMESTAMP AS TimeOfOfferChange,
        offers.value:IsBuyBoxWinner::BOOLEAN AS IsBuyBoxWinner,    
        offers.value:IsFeaturedMerchant::BOOLEAN AS IsFeaturedMerchant,    
        offers.value:IsFulfilledByAmazon::BOOLEAN AS IsFulfilledByAmazon,    
        offers.value:ListingPrice:Amount::FLOAT AS OfferListingPriceAmount,    
        offers.value:ListingPrice:CurrencyCode::STRING AS OfferListingPriceCurrencyCode,   
        offers.value:PrimeInformation:IsOfferNationalPrime::BOOLEAN AS IsOfferNationalPrime, 
        offers.value:PrimeInformation:IsOfferPrime::BOOLEAN AS IsOfferPrime,   
        offers.value:SellerFeedbackRating:FeedbackCount::INTEGER AS SellerFeedbackCount,   
        offers.value:SellerFeedbackRating:SellerPositiveFeedbackRating::INTEGER AS SellerPositiveFeedbackRating,  
        offers.value:SellerId::STRING AS SellerId,    
        offers.value:Shipping:Amount::FLOAT AS OffersShippingAmount,  
        offers.value:Shipping:CurrencyCode::STRING AS OffersShippingCurrencyCode,    
        offers.value:ShippingTime:AvailabilityType::STRING AS ShippingAvailabilityType,   
        offers.value:ShippingTime:MaximumHours::INTEGER AS ShippingMaxHours,   
        offers.value:ShippingTime:MinimumHours::INTEGER AS ShippingMinHours,   
        offers.value:ShipsDomestically::BOOLEAN AS ShipsDomestically,  
        offers.value:ShipsFrom:Country::STRING AS ShipsFromCountry,   
        offers.value:ShipsFrom:State::STRING AS ShipsFromState,   
        offers.value:SubCondition::STRING AS SubCondition,
        summary.value:Condition::STRING as SummaryCondition,
        summary.value:LandedPrice::Object:Amount::FLOAT as LandedAmount,
        summary.value:LandedPrice::Object:CurrencyCode::STRING as LandedPriceCurrencyCode,
        summary.value:ListingPrice::Object:Amount::FLOAT as SummaryListingPriceAmount,
        summary.value:ListingPrice::Object:CurrencyCode::STRING as ListingPriceCurrencyCode,
        summary.value:Shipping::Object:Amount::FLOAT as SummaryShippingAmount,
        summary.value:Shipping::Object:CurrencyCode::STRING as SummaryShippingCurrencyCode,
        ListPrice.value:Amount::Float as ListPriceAmount,
        ListPrice.value:CurrencyCode::STRING as ListPriceCurrencyCode,
        LowestPrices.value:Condition::STRING as LowestPricesCondition,
        LowestPrices.value:FulfillmentChannel::STRING as FulfillmentChannel,
        LowestPrices.value:LandedPrice::Object:Amount::Float as LowestLandedPriceAmount,
        LowestPrices.value:LandedPrice::Object:CurrencyCode::STRING as LowestLandedPriceCurrencyCode,
        LowestPrices.value:ListingPrice::Object:Amount::Float as LowestListingPriceAmount,
        LowestPrices.value:ListingPrice::Object:CurrencyCode::STRING as LowestListingPriceCurrencyCode,
        LowestPrices.value:Shipping::Object:Amount::Float as LowestShippingAmount,
        LowestPrices.value:Shipping::Object:CurrencyCode::STRING as LowestShippingCurrencyCode,
        nofbeo.value:Condition::STRING as NoEligBuyboxCondition,
        nofbeo.value:FulfillmentChannel::STRING as NoEligBuyboxFulfillmentChannel,
        nofbeo.value:OfferCount::STRING as NoEligBuyboxOfferCount,
        NumberOfOffers.value:Condition::STRING as NumberOfOffersCondition,
        NumberOfOffers.value:FulfillmentChannel::STRING as NumberOfOffersFulfilmentChanel,
        NumberOfOffers.value:OfferCount::STRING as NumberOfOffersOfferCount,
        SalesRankings.value:ProductCategoryId::STRING as SalesRaningProductCategoryId,
        SalesRankings.value:Rank::BIGINT as SalesRaningRank,

    FROM source_data,
    LATERAL FLATTEN(input => offer) AS offer,
    LATERAL FLATTEN(input => offers) AS offers,
    LATERAL FLATTEN(input => summary) AS summary,
    LATERAL FLATTEN(input => ListPrice) AS ListPrice,
    LATERAL FLATTEN(input => LowestPrices) AS LowestPrices,
    LATERAL FLATTEN(input => NumberOfBuyBoxEligibleOffers) AS nofbeo,
    LATERAL FLATTEN(input => NumberOfOffers) AS NumberOfOffers,
    LATERAL FLATTEN(input => SalesRankings) AS SalesRankings
    
)
SELECT *
FROM flatten_payload
